# -*- mode: ruby -*-
# vi: set ft=ruby :

$os_update = <<SCRIPT
#!/bin/bash
echo "Updating all the packages from the system"
apt update && apt upgrade -y
SCRIPT

$jenkins_install = <<SCRIPT
#!/bin/bash
curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee \
  /usr/share/keyrings/jenkins-keyring.asc > /dev/null
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null
sudo apt-get update
sudo apt-get install jenkins -y
sudo systemctl start jenkins
SCRIPT

$java_install = <<SCRIPT
#!/bin/bash
echo "Downloading java on the system"
sudo apt update
sudo apt install openjdk-11-jre-headless -y
SCRIPT

$nginx_install = <<SCRIPT
#!/bin/bash
sudo apt install nginx -y
SCRIPT



Vagrant.configure("2") do |config|
 
  config.vm.define "Operator" do |operator|
      operator.vm.box = "ubuntu/focal64"
      operator.vm.hostname = "Operator"
      operator.vm.network "private_network", ip: "192.168.56.30"
      operator.vm.provision "shell", :inline =>$os_update 
      operator.vm.provision "shell", :inline =>$java_install
      operator.vm.provision "shell", :inline =>$jenkins_install  
      
  end
  config.vm.define "Environment" do |environment|
    environment.vm.box = "ubuntu/focal64"
    environment.vm.hostname = "Environment"
    environment.vm.network "private_network", ip: "192.168.56.31"
    environment.vm.provision "shell", :inline =>$os_update 
    environment.vm.provision "shell", :inline =>$nginx_install 
    
   end
end