# -*- mode: ruby -*-
# vi: set ft=ruby :

# ssh-keygen -t rsa -b 4096 -C "ansible"

$os_packages_update = <<SCRIPT
#!/bin/bash
  echo "Update OS packages..."
  apt update && apt upgrade -y 
  
SCRIPT

$docker_install = <<SCRIPT
#!/bin/bash
    echo "Docker install..."
    apt install docker.io -y
    
SCRIPT

$user_setup = <<SCRIPT
#!/bin/bash
function create_user {
  USER_EXISTS=0
  USERS=`getent passwd | cut -d":" -f1`
  
  for USER in $USERS;
  do
    if [[ $1 == $USER ]]; then
      echo "$1 user exists"
      USER_EXISTS=1
    fi
  done
  if [[ $USER_EXISTS -eq 0 ]]; then
    echo "Creating user: $1"
    adduser --disabled-password --gecos "" $1
  fi
}
create_user "jenkins"
sleep 1m
SCRIPT


$jenkins_install_plugins = <<SCRIPT
#!/bin/bash
echo "Install Jenkins plugins"
sudo chmod +x /vagrant/files/plugins.sh
sudo bash /vagrant/files/plugins.sh
sudo systemctl daemon-reload
sudo service jenkins restart

SCRIPT

$jenkins_setup_war_package = <<SCRIPT
#!/bin/bash
  echo " Installing Jenkins war package..."
  echo " Installing Jenkins dependencies..."
  sudo apt install openjdk-11-jre -y
  
  # Check if Jenkins dir exists
  if [ ! -d /opt/jenkins ]; then
    mkdir /opt/jenkins
  fi
  # Check if file jenkins.war exists
  if [ ! -f /opt/jenkins/jenkins.war ]; then
    wget  --directory-prefix=/opt/jenkins https://get.jenkins.io/war/2.349/jenkins.war 
  fi
  
  if [ ! -d /opt/jenkins/plugins ]; then
    mkdir /opt/jenkins/plugins
  fi
  
  echo "---------Installing the plugins------------"
  
  #vim /vagrant/files/plugins.sh -------Make shell script for plugins


  sudo chmod u+x /vagrant/files/plugins.sh
  sudo sh /vagrant/files/plugins.sh


  chown -R jenkins:jenkins /opt/jenkins
  usermod -aG docker jenkins
 

  if [ ! -f /lib/systemd/system/jenkins.service ]; then
    if [ ! -f /vagrant/files/jenkins.service ]; then
      echo "Make sure vagrant folder is mounted and/or the jenkins.service file exists."
      exit      
    fi

    
    cp /vagrant/files/jenkins.service /lib/systemd/system


    sudo chown -R  jenkins:jenkins jenkins
    sudo systemctl daemon-reload
    sudo systemctl enable jenkins.service
    sudo systemctl start jenkins.service
    sudo service jenkins restart
  fi
  
SCRIPT

$jenkins_install_plugins = <<SCRIPT
#!/bin/bash

if [ ! -d /opt/jenkins/plugins ]; then
  mkdir /opt/jenkins/plugins
fi

echo "---------Installing the plugins------------"

#vim /vagrant/files/plugins.sh -------Make shell script for plugins

sudo chmod +x /vagrant/files/plugins.sh
sudo sh /vagrant/files/plugins.sh

echo "---------Make Jenkins ready--------------"

sudo systemctl daemon-reload
sudo systemctl enable jenkins.service
sudo systemctl start jenkins.service
sudo service jenkins restart

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "cicd_server" do |jk|
    jk.vm.hostname = "jenkins"
    jk.vm.network "private_network", ip: "192.168.56.30"
      jk.vm.provider "virtualbox" do |vb|
         vb.cpus = 2
         vb.memory = 4096
      end
    jk.vm.provision "shell", :inline => $os_packages_update
    jk.vm.provision "shell", :inline => $docker_install
    jk.vm.provision "shell", :inline => $user_setup
    jk.vm.provision "shell", :inline => $jenkins_setup_war_package
   # jk.vm.provision "shell", :inline => $jenkins_install_plugins
    
  end

  config.vm.define "env_server" do |dk|
    dk.vm.hostname = "docker"
    dk.vm.network "private_network", ip: "192.168.56.31"
      dk.vm.provider "virtualbox" do |vb|
          vb.cpus = 2
          vb.memory = 4096
      end
    dk.vm.provision "shell", :inline => $os_packages_update
    dk.vm.provision "shell", :inline => $docker_install
  end
end
